### ISSUE TITLE
:dart: DM Knowledg Base - Roadmap 2023

### ISSUE THREAD

**Issue by vshitov** [Tinkoff/dm-knowledgebase#5]
Это наш примерный план, который даёт понимание куда будет развиваться наш продукт.

## 🚀  Version 1 - Q1 2021
- [ ] https://github.com/Tinkoff/dm-knowledgebase/issues/3
- [ ] Карта развития Delivery Manager

## 🚀  Version 2 - Q2 2021
- [ ] Онбординг в профессию
- [ ] Онбординг профессии в компанию

**Comment by pavelpower** [comment]
* [ ] Как работать с Delivery Manager-ом если я его нанимаю
* [ ] Как работать с DM если он работает над улучшением процессоов в моем напарвлении
